set $term alacritty
set $term_cwd alacritty --working-directory "$(swaycwd 2>/dev/null || echo $HOME)"

set $bindsym bindsym
set $unbindsym unbindsym

set $background $HOME/Pictures/wallpapers/wallhaven-9dky2w_3840x2160.png
set $apply_background swaymsg 'output * bg $background fill'
