input "1149:8257:Kensington_Kensington_Slimblade_Trackball" {
    #accel_profile "flat" # disable mouse acceleration (enabled by default; to set it manually, use "adaptive" instead of "flat")
    pointer_accel 0.3 # set mouse sensitivity (between -1 and 1)
}
